In [198]:
import pandas as pd
import numpy as np

In [199]:
df=pd.read_csv("Top Indian Places to Visit.csv")

In [200]:
df

,Unnamed: 0,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Weekly Off,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
0,0,Northern,Delhi,Delhi,India Gate,War Memorial,1921,0.5,4.6,0,Yes,NaN,Historical,Yes,2.60,Evening
1,1,Northern,Delhi,Delhi,Humayun's Tomb,Tomb,1572,2.0,4.5,30,Yes,NaN,Historical,Yes,0.40,Afternoon
2,2,Northern,Delhi,Delhi,Akshardham Temple,Temple,2005,5.0,4.6,60,Yes,NaN,Religious,No,0.40,Afternoon
3,3,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019,2.0,4.1,50,Yes,Monday,Environmental,Yes,0.27,Evening
4,4,Northern,Delhi,Delhi,Jantar Mantar,Observatory,1724,2.0,4.2,15,Yes,NaN,Scientific,Yes,0.31,Morning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,320,Western,Gujarat,Gandhinagar,Akshardham,Temple,1992,3.0,4.6,0,Yes,Monday,Religious,No,0.18,All
321,321,Central,Uttar Pradesh,Agra,Agra Fort,Fort,1565,2.0,4.5,40,Yes,NaN,Historical,Yes,1.30,Afternoon
322,322,Central,Madhya Pradesh,Bhopal,Madhya Pradesh Tribal Museum,Museum,2013,2.0,4.7,10,Yes,Monday,Cultural,Yes,0.15,All
323,323,Northern,Rajasthan,Jaipur,City Palace,Palace,1727,2.0,4.4,200,Yes,NaN,Historical,Yes,0.51,Morning
324,324,Northern,Rajasthan,Jaipur,Albert Hall Museum,Museum,1887,2.0,4.5,200,Yes,NaN,Historical,Yes,0.63,All

In [201]:
dfx=df.dropna()
dfx

,Unnamed: 0,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Weekly Off,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
3,3,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019,2.0,4.1,50,Yes,Monday,Environmental,Yes,0.270,Evening
5,5,Northern,Delhi,Delhi,Chandni Chowk,Market,1700,3.0,4.2,0,Yes,Sunday,Market,Yes,0.250,Afternoon
6,6,Northern,Delhi,Delhi,Lotus Temple,Temple,1986,1.0,4.5,0,Yes,Monday,Religious,Yes,0.590,Evening
12,12,Northern,Delhi,Delhi,National Gallery of Modern Art,Museum,1954,3.0,4.5,20,Yes,Monday,Artistic,Yes,0.080,All
13,13,Northern,Delhi,Delhi,National Zoological Park,Zoo,1959,3.0,4.1,80,Yes,Friday,Environmental,Yes,0.410,All
19,19,Western,Maharastra,Mumbai,Sanjay Gandhi National Park,National Park,1996,3.0,4.3,50,Yes,Monday,Wildlife,Yes,0.600,All
26,26,Western,Maharastra,Lonavala,Imagicaa,Amusement Park,2013,5.0,1.4,1149,No,Monday,Recreational,Yes,0.950,All
27,27,Southern,Karnataka,Bangalore,Bangalore Palace,Palace,1878,2.0,4.2,500,Yes,Monday,Historical,Yes,0.900,Morning
32,32,Southern,Telangana,Hyderabad,Charminar,Landmark,1591,1.0,4.5,25,Yes,Friday,Historical,Yes,2.100,Morning
42,42,Eastern,West Bengal,Kolkata,Victoria Memorial,Museum,1921,1.5,4.6,30,Yes,Monday,Historical,Yes,0.730,Morning
44,44,Eastern,West Bengal,Kolkata,Indian Museum,Museum,1814,2.0,4.6,50,Yes,Monday,Historical,Yes,0.180,Morning
70,70,Western,Gujarat,Vadodara,Laxmi Vilas Palace,Palace,1890,2.0,4.4,200,Yes,Monday,Historical,Yes,0.170,Afternoon
73,73,Western,Gujarat,Kevadia,Statue of Unity,Monument,2018,3.0,4.6,350,No,Monday,Historical,Yes,0.670,All
78,78,Western,Gujarat,Ahmedabad,Science City,Science,2002,7.0,4.4,500,Yes,Monday,Educational,Yes,0.110,All
109,109,Southern,Kerala,Kochi,Kerala Folklore Museum,Cultural,2009,1.5,4.4,100,Yes,Monday,Cultural,Yes,0.100,All
124,124,Western,Maharastra,Aurangabad,Ajanta Caves,Cave,200,3.0,4.6,30,Yes,Monday,Historical,Yes,0.210,Afternoon
131,131,Western,Maharastra,Lonavala,Karla Caves,Cave,200,1.5,4.4,25,Yes,Yes,Historical,Yes,0.270,Afternoon
135,135,Western,Maharashtra,Ajanta,Ellora Caves,Cave,600,3.0,4.7,30,Yes,Tuesday,Historical,Yes,0.490,Afternoon
181,181,Central,Uttar Pradesh,Agra,Taj Mahal,Mausoleum,1632,2.0,4.6,50,Yes,Friday,Historical,Yes,2.250,Morning
183,183,Central,Uttar Pradesh,Lucknow,Bara Imambara,Monument,1784,1.5,4.4,50,Yes,Monday,Historical,No,0.450,All
194,194,Central,Uttar Pradesh,Kanpur,Allen Forest Zoo,Zoo,1971,2.0,4.2,150,Yes,Monday,Wildlife,Yes,0.210,All
219,219,Eastern,West Bengal,Murshidabad,Hazarduari Palace,Palace,1837,1.5,4.5,10,Yes,Friday,Historical,Yes,0.180,Morning
223,223,Eastern,West Bengal,Cooch Behar,Cooch Behar Palace,Palace,1887,1.0,4.5,20,Yes,Friday,Historical,Yes,0.090,All
263,263,Southern,Andhra Pradesh,Visakhapatnam,Indira Gandhi Zoological Park,Zoo,1977,2.0,4.1,20,Yes,Monday,Wildlife,Yes,0.250,Afternoon
282,282,North Eastern,Tripura,Agartala,Ujjayanta Palace,Palace,1901,1.5,4.5,10,Yes,Monday,Historical,Yes,0.035,All
290,290,Southern,Andaman and Nicobar Islands,Port Blair,Cellular Jail,Landmark,1906,1.5,4.7,30,Yes,Monday,Historical,Yes,0.120,Afternoon
302,302,Northern,Haryana,Gurugram,Kingdom of Dreams,Entertainment,2010,3.0,4.4,1100,Yes,Monday,Entertainment,Yes,0.300,Afternoon
310,310,Eastern,Odisha,Bhubaneswar,Nandankanan Zoological Park,Zoo,1960,3.0,4.4,50,Yes,Monday,Wildlife,Yes,0.810,Afternoon
315,315,Central,Uttar Pradesh,Greater Noida,Buddh International Circuit,Race Track,2011,2.0,4.6,1500,Yes,Sunday,Sports,Yes,7.400,All
318,318,Northern,Delhi,New Delhi,Rail Museum,Museum,1977,2.0,4.4,50,Yes,Monday,Cultural,Yes,0.240,Morning
320,320,Western,Gujarat,Gandhinagar,Akshardham,Temple,1992,3.0,4.6,0,Yes,Monday,Religious,No,0.180,All
322,322,Central,Madhya Pradesh,Bhopal,Madhya Pradesh Tribal Museum,Museum,2013,2.0,4.7,10,Yes,Monday,Cultural,Yes,0.150,All

In [202]:
dfmoney = df[df['Entrance Fee in INR'] != 0]

In [203]:
dfmoney=df.dropna()

In [204]:
df.nunique()

Unnamed: 0                          325
Zone                                  6
State                                33
City                                214
Name                                321
Type                                 78
Establishment Year                  162
time needed to visit in hrs          11
Google review rating                 14
Entrance Fee in INR                  33
Airport with 50km Radius              2
Weekly Off                            5
Significance                         25
DSLR Allowed                          2
Number of google review in lakhs    108
Best Time to visit                    7
dtype: int64

In [205]:
df2=df[['Type','Google review rating','Number of google review in lakhs']]
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 3 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Type                              325 non-null    object
 1   Google review rating              325 non-null    float64
 2   Number of google review in lakhs  325 non-null    float64
dtypes: float64(2), object(1)
memory usage: 7.7+ KB

In [206]:
df2=pd.get_dummies(df2,dtype=int)
df2

,Google review rating,Number of google review in lakhs,Type_Adventure Sport,Type_Amusement Park,Type_Aquarium,Type_Beach,Type_Bird Sanctuary,Type_Border Crossing,Type_Botanical Garden,Type_Bridge,...,Type_Trekking,Type_Urban Development Project,Type_Valley,Type_Viewpoint,Type_Village,Type_Vineyard,Type_War Memorial,Type_Waterfall,Type_Wildlife Sanctuary,Type_Zoo
0,4.6,2.60,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,4.5,0.40,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4.6,0.40,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4.1,0.27,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4.2,0.31,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,4.6,0.18,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
321,4.5,1.30,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
322,4.7,0.15,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
323,4.4,0.51,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
324,4.5,0.63,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [207]:
X1=dfmoney
Y1=dfmoney['Entrance Fee in INR']
from sklearn.model_selection import train_test_split
X_train_1,X_test_1,Y_train_1,Y_test_1=train_test_split(X1,Y1,test_size=0.15)

In [208]:
from sklearn.linear_model import LinearRegression 
traintestmodel=LinearRegression()
traintestmodel.fit(X1,Y1)

ValueError: could not convert string to float: 'Northern'

In [ ]:
traintestmodel.score(X_train_1,Y_train_1)

In [ ]:
traintestmodel.score(X_test_1,Y_test_1)

In [ ]:
traintestmodel.score(X1,Y1)

In [ ]:
from sklearn.linear_model import Lasso
traintestmodel2=Lasso(alpha=20,max_iter=75,tol=0.1)
traintestmodel2.fit(X1,Y1)

In [ ]:
traintestmodel2.score(X_train_1,Y_train_1)

In [ ]:
traintestmodel2.score(X_test_1,Y_test_1)

In [ ]:
traintestmodel2.score(X1,Y1)

In [ ]:
from sklearn.linear_model import Ridge
traintestmodel3=Ridge(alpha=25,max_iter=75,tol=0.1)
traintestmodel3.fit(X1,Y1)

In [ ]:
traintestmodel3.score(X_train_1,Y_train_1)

In [ ]:
traintestmodel3.score(X_test_1,Y_test_1)

In [ ]:
traintestmodel3.score(X1,Y1)